"""Update on Migration

Revision ID: 368032540c2b
Revises: 2d51df3ab219
Create Date: 2018-05-23 08:40:44.362001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368032540c2b'
down_revision = '2d51df3ab219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitches_id'], ['id'])
    op.add_column('pitches', sa.Column('commentcommencommen', sa.String(), nullable=True))
    op.drop_column('pitches', 'vote')
    op.drop_column('pitches', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'commentcommencommen')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitches_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
