"""Updated Migration

Revision ID: 70f5c80ad168
Revises: 368032540c2b
Create Date: 2018-05-23 19:28:34.011440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f5c80ad168'
down_revision = '368032540c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitches_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitches_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('pitches', 'commentcommencommen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('commentcommencommen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'comment')
    op.drop_table('votes')
    # ### end Alembic commands ###
